# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ask_and_answer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Hỏi Đáp")
        MainWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(650, 10, 141, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStart.setAutoFillBackground(False)
        self.btnStart.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.btnStart.setObjectName("btnStart")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(650, 70, 141, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit.setFont(font)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExit.setAutoFillBackground(False)
        self.btnExit.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.btnExit.setObjectName("btnExit")
        self.txtCauHoi = QtWidgets.QLabel(self.centralwidget)
        self.txtCauHoi.setGeometry(QtCore.QRect(0, 10, 630, 200))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(11)
        font.setItalic(True)
        self.txtCauHoi.setFont(font)
        self.txtCauHoi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtCauHoi.setObjectName("txtCauHoi")
        self.cbbMonHoc = QtWidgets.QComboBox(self.centralwidget)
        self.cbbMonHoc.setGeometry(QtCore.QRect(650, 160, 140, 30))
        self.cbbMonHoc.setObjectName("cbbMonHoc")
        self.txtMonHoc = QtWidgets.QLabel(self.centralwidget)
        self.txtMonHoc.setGeometry(QtCore.QRect(650, 130, 140, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(11)
        self.txtMonHoc.setFont(font)
        self.txtMonHoc.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMonHoc.setObjectName("txtMonHoc")
        self.cbbSoCauHoi = QtWidgets.QComboBox(self.centralwidget)
        self.cbbSoCauHoi.setGeometry(QtCore.QRect(650, 230, 140, 30))
        self.cbbSoCauHoi.setCurrentText("")
        self.cbbSoCauHoi.setObjectName("cbbSoCauHoi")

        self.txtSoCauHoi = QtWidgets.QLabel(self.centralwidget)
        self.txtSoCauHoi.setGeometry(QtCore.QRect(650, 200, 140, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(11)
        self.txtSoCauHoi.setFont(font)
        self.txtSoCauHoi.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSoCauHoi.setObjectName("txtSoCauHoi")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 640, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.txtDapAnA = QtWidgets.QLabel(self.centralwidget)
        self.txtDapAnA.setGeometry(QtCore.QRect(0, 190, 630, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(11)
        font.setItalic(True)
        self.txtDapAnA.setFont(font)
        self.txtDapAnA.setText("")
        self.txtDapAnA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtDapAnA.setObjectName("txtDapAnA")
        self.txtDapAnB = QtWidgets.QLabel(self.centralwidget)
        self.txtDapAnB.setGeometry(QtCore.QRect(0, 240, 630, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(11)
        font.setItalic(True)
        self.txtDapAnB.setFont(font)
        self.txtDapAnB.setText("")
        self.txtDapAnB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtDapAnB.setObjectName("txtDapAnB")
        self.txtDapAnC = QtWidgets.QLabel(self.centralwidget)
        self.txtDapAnC.setGeometry(QtCore.QRect(0, 290, 630, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(11)
        font.setItalic(True)
        self.txtDapAnC.setFont(font)
        self.txtDapAnC.setText("")
        self.txtDapAnC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtDapAnC.setObjectName("txtDapAnC")
        self.txtDapAnD = QtWidgets.QLabel(self.centralwidget)
        self.txtDapAnD.setGeometry(QtCore.QRect(0, 340, 630, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(11)
        font.setItalic(True)
        self.txtDapAnD.setFont(font)
        self.txtDapAnD.setText("")
        self.txtDapAnD.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtDapAnD.setObjectName("txtDapAnD")
        self.txtKetQua = QtWidgets.QLabel(self.centralwidget)
        self.txtKetQua.setGeometry(QtCore.QRect(650, 270, 140, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        self.txtKetQua.setFont(font)
        self.txtKetQua.setAlignment(QtCore.Qt.AlignCenter)
        self.txtKetQua.setObjectName("txtKetQua")
        self.txtResult = QtWidgets.QLabel(self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(650, 310, 140, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        font.setBold(True)
        self.txtResult.setFont(font)
        self.txtResult.setAlignment(QtCore.Qt.AlignCenter)
        self.txtResult.setObjectName("txtResult")
        self.txtImage = QtWidgets.QLabel(self.centralwidget)
        self.txtImage.setGeometry(QtCore.QRect(0, 0, 640, 400))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(11)
        font.setItalic(True)
        self.txtImage.setFont(font)
        self.txtImage.setText("")
        self.txtImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtImage.setObjectName("txtImage")
        self.graphicsView.raise_()
        self.btnStart.raise_()
        self.btnExit.raise_()
        self.txtCauHoi.raise_()
        self.cbbMonHoc.raise_()
        self.txtMonHoc.raise_()
        self.cbbSoCauHoi.raise_()
        self.txtSoCauHoi.raise_()
        self.txtDapAnA.raise_()
        self.txtDapAnB.raise_()
        self.txtDapAnC.raise_()
        self.txtDapAnD.raise_()
        self.txtKetQua.raise_()
        self.txtResult.raise_()
        self.txtImage.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Setup label
        self.txtCauHoi.setWordWrap(True)
        self.txtDapAnA.setWordWrap(True)
        self.txtDapAnB.setWordWrap(True)
        self.txtDapAnC.setWordWrap(True)
        self.txtDapAnD.setWordWrap(True)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thi vấn đáp"))
        self.btnStart.setText(_translate("MainWindow", "Bắt đầu"))
        self.btnExit.setText(_translate("MainWindow", "Thoát"))
        self.txtCauHoi.setText(_translate("MainWindow", ""))
        self.txtMonHoc.setText(_translate("MainWindow", "Môn học "))
        self.txtSoCauHoi.setText(_translate("MainWindow", "Số câu hỏi"))
        self.txtKetQua.setText(_translate("MainWindow", "Kết quả"))
        self.txtResult.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ef2929;\">0/3</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
